### ISSUE TITLE
object does not have member

### ISSUE THREAD

**Issue by jsarenik** [lightningamp/esplora_clnd_plugin#47] opened 2021-03-28 18:04 UTC
```
$ lightningd --testnet --disable-plugin bcli --esplora-api-endpoint=https://blockstream.info/testnet/api --proxy=127.0.0.1:9050
...
2021-03-28T17:52:36.545Z INFO    plugin-esplora: getutxout
2021-03-28T17:52:38.374Z INFO    plugin-esplora: getutxout
2021-03-28T17:52:40.264Z INFO    plugin-esplora: getutxout
2021-03-28T17:52:41.884Z INFO    plugin-esplora: getutxout
2021-03-28T17:52:44.060Z INFO    plugin-esplora: getutxout
2021-03-28T17:52:45.857Z INFO    plugin-esplora: getutxout
2021-03-28T17:52:47.590Z INFO    plugin-esplora: getutxout
/home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/esplora error: bad response to getutxout (bad 'result' field: Parsing '{result:': object does not have member result), response was {"jsonrpc":"2.0","id":115,"error":{"code":400,"message":"getutxout: json error ({\"txid\":)?"} }
2021-03-28T17:52:47.591Z **BROKEN** lightningd: /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/esplora error: bad response to getutxout (bad 'result' field: Parsing '{result:': object does not have member result), response was {"jsonrpc":"2.0","id":115,"error":{"code":400,"message":"getutxout: json error ({\"txid\":)?"} }
lightningd: FATAL SIGNAL 6 (version v0.10.0rc2-1-gda918b6)
0x563c1c054bd7 send_backtrace
	common/daemon.c:39
0x563c1c054c81 crashdump
	common/daemon.c:52
0x7f8fd129420f ???
	???:0
0x7f8fd129418b ???
	???:0
0x7f8fd1273858 ???
	???:0
0x563c1c002721 fatal
	lightningd/log.c:803
0x563c1bfda5c3 bitcoin_plugin_error
	lightningd/bitcoind.c:120
0x563c1bfdb2e4 getutxout_callback
	lightningd/bitcoind.c:534
0x563c1c025100 plugin_response_handle
	lightningd/plugin.c:460
0x563c1c025310 plugin_read_json_one
	lightningd/plugin.c:566
0x563c1c0254da plugin_read_json
	lightningd/plugin.c:611
0x563c1c0a93bc next_plan
	ccan/ccan/io/io.c:59
0x563c1c0a9fa1 do_plan
	ccan/ccan/io/io.c:407
0x563c1c0a9fe3 io_ready
	ccan/ccan/io/io.c:417
0x563c1c0ac27b io_loop
	ccan/ccan/io/poll.c:445
0x563c1bffa0d8 io_loop_with_timers
	lightningd/io_loop_with_timers.c:24
0x563c1bfffc99 main
	lightningd/lightningd.c:1102
0x7f8fd12750b2 ???
	???:0
0x563c1bfd9ffd ???
	???:0
0xffffffffffffffff ???
	???:0
2021-03-28T17:52:47.611Z **BROKEN** lightningd: FATAL SIGNAL 6 (version v0.10.0rc2-1-gda918b6)
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: common/daemon.c:44 (send_backtrace) 0x563c1c054c2d
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: common/daemon.c:52 (crashdump) 0x563c1c054c81
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f8fd129420f
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f8fd129418b
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f8fd1273858
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: lightningd/log.c:803 (fatal) 0x563c1c002721
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: lightningd/bitcoind.c:120 (bitcoin_plugin_error) 0x563c1bfda5c3
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: lightningd/bitcoind.c:534 (getutxout_callback) 0x563c1bfdb2e4
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:460 (plugin_response_handle) 0x563c1c025100
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:566 (plugin_read_json_one) 0x563c1c025310
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:611 (plugin_read_json) 0x563c1c0254da
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x563c1c0a93bc
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:407 (do_plan) 0x563c1c0a9fa1
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:417 (io_ready) 0x563c1c0a9fe3
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: ccan/ccan/io/poll.c:445 (io_loop) 0x563c1c0ac27b
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: lightningd/io_loop_with_timers.c:24 (io_loop_with_timers) 0x563c1bffa0d8
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: lightningd/lightningd.c:1102 (main) 0x563c1bfffc99
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f8fd12750b2
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x563c1bfd9ffd
2021-03-28T17:52:47.611Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0xffffffffffffffff
Log dumped in crash.log.20210328175247
autoclean: txprepare: spenderp: pay: Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.



keysend: Lost connection to the RPC socket.
Aborted
```

One thing I just realized is that I am using wrong codebase in https://github.com/jsarenik/lightning/pull/1 so I will update from https://github.com/lvaccaro/esplora_clnd_plugin to https://github.com/lightningamp/esplora_clnd_plugin

**Comment by jsarenik** [comment] 2021-03-28 19:01
Seems to be fixed by 2bf24a3. Thank you @vincenzopalazzo !

**Comment by vincenzopalazzo** [comment] 2021-03-28 19:04
amazing @jsarenik  :-D

**Comment by vincenzopalazzo** [comment] 2021-03-28 19:15
@jsarenik ufortunatlly my fix is over another method (sendrawtx) and not on the `getutxout`, this looks like related to https://github.com/lightningamp/esplora_clnd_plugin/issues/39 

Can you put also your network and information related to your node, like the getinfo result.

**Comment by jsarenik** [comment] 2021-03-29 09:37
Sure. Thanks for feed-back and noticing my impression was wrong. I do not have any clear steps to reproduce the issue and I was just guessing that maybe it got fixed.

It is running jsarenik/lightning@4ac416884 (`v0.10.0-rc2` with `esplora` added)

Here is `getinfo`:

```
{
   "id": "0299edd3eb05ca4c55f39775a0677a74ce80c8e86e3cd669cdf4cea50697c7ba0f",
   "alias": "LOUDBAGEL-v0.10.0rc2-1-g4ac4168",
   "color": "0299ed",
   "num_peers": 2,
   "num_pending_channels": 0,
   "num_active_channels": 2,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv6",
         "address": "2001:470:1f1b:365:4ad7:5ff:fec0:6beb",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.10.0rc2-1-g4ac4168",
   "blockheight": 1968391,
   "network": "testnet",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/nsm/.lightning/testnet"
}
```

I am running `lightningd` from a script like this:

```
exec lightningd \
  --testnet \
  --log-level=debug \
  --disable-plugin bcli \
  --esplora-api-endpoint=https://blockstream.info/testnet/api \
  --proxy=127.0.0.1:9050
```

**Comment by vincenzopalazzo** [comment] 2021-03-29 10:52
>Sure. Thanks for feed-back and noticing my impression was wrong. I do not have any clear steps to reproduce the issue and I was just guessing that maybe it got fixed.

Me too, I pass one week to reproduce these bugs with esplora but only sometimes happened, unfortunately. Maybe there is any reason under the hood

We hope to fix it soon!

**Comment by jsarenik** [comment] 2021-03-29 11:48
Here is the most recent. No steps to reproduce, just keep esplora-enabled `lightningd --testnet` running.

```
2021-03-29T10:21:42.401Z INFO    plugin-esplora: getrawblockbyheight 1384633
2021-03-29T10:21:42.401Z INFO    plugin-esplora: blockhash: 00000000000000202d800545e7c5b36f8e61829286e442e040451b1d670c2471 from https://blockstream.info/testnet/api/block-height/1384633
2021-03-29T10:21:43.425Z INFO    plugin-esplora: getutxout
2021-03-29T10:21:43.871Z INFO    plugin-esplora: getutxout
2021-03-29T10:21:44.410Z INFO    plugin-esplora: getutxout
2021-03-29T10:21:44.926Z INFO    plugin-esplora: getutxout
2021-03-29T10:21:45.351Z INFO    plugin-esplora: getutxout
2021-03-29T10:21:46.331Z INFO    plugin-esplora: getutxout
2021-03-29T10:21:47.311Z INFO    plugin-esplora: getutxout
2021-03-29T10:21:47.846Z INFO    plugin-esplora: getutxout
2021-03-29T10:21:48.381Z INFO    plugin-esplora: getutxout
2021-03-29T10:21:49.324Z INFO    plugin-esplora: getrawblockbyheight 1384636
2021-03-29T10:21:49.324Z INFO    plugin-esplora: blockhash: 000000000000003da443ae57f062792a01a3d38af75345cb0b291a2129f42e68 from https://blockstream.info/testnet/api/block-height/1384636
2021-03-29T10:21:50.256Z DEBUG   plugin-esplora: Log pruned 231 entries (mem 10485906 -> 2161407)
2021-03-29T10:21:50.256Z INFO    plugin-esplora: getutxout
/home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/esplora error: bad response to getutxout (bad 'result' field: Parsing '{result:{script:%,amount:': object does not have member amount), response was {"jsonrpc":"2.0","id":1843,"result":{"script":"0020a40e801531fdca0fb550013a9140aaaf8d9eb106c427258fbc86d0e0c52c432d"} }
2021-03-29T10:21:50.257Z **BROKEN** lightningd: /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/esplora error: bad response to getutxout (bad 'result' field: Parsing '{result:{script:%,amount:': object does not have member amount), response was {"jsonrpc":"2.0","id":1843,"result":{"script":"0020a40e801531fdca0fb550013a9140aaaf8d9eb106c427258fbc86d0e0c52c432d"} }
lightningd: FATAL SIGNAL 6 (version v0.10.0rc2-1-g4ac4168)
0x55eb54084bd7 send_backtrace
	common/daemon.c:39
0x55eb54084c81 crashdump
	common/daemon.c:52
0x7f8be8f9120f ???
	???:0
0x7f8be8f9118b ???
	???:0
0x7f8be8f70858 ???
	???:0
0x55eb54032721 fatal
	lightningd/log.c:803
0x55eb5400a5c3 bitcoin_plugin_error
	lightningd/bitcoind.c:120
0x55eb5400b2e4 getutxout_callback
	lightningd/bitcoind.c:534
0x55eb54055100 plugin_response_handle
	lightningd/plugin.c:460
0x55eb54055310 plugin_read_json_one
	lightningd/plugin.c:566
0x55eb540554da plugin_read_json
	lightningd/plugin.c:611
0x55eb540d93bc next_plan
	ccan/ccan/io/io.c:59
0x55eb540d9fa1 do_plan
	ccan/ccan/io/io.c:407
0x55eb540d9fe3 io_ready
	ccan/ccan/io/io.c:417
0x55eb540dc27b io_loop
	ccan/ccan/io/poll.c:445
0x55eb5402a0d8 io_loop_with_timers
	lightningd/io_loop_with_timers.c:24
0x55eb5402fc99 main
	lightningd/lightningd.c:1102
0x7f8be8f720b2 ???
	???:0
0x55eb54009ffd ???
	???:0
0xffffffffffffffff ???
	???:0
2021-03-29T10:21:50.276Z **BROKEN** lightningd: FATAL SIGNAL 6 (version v0.10.0rc2-1-g4ac4168)
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: common/daemon.c:44 (send_backtrace) 0x55eb54084c2d
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: common/daemon.c:52 (crashdump) 0x55eb54084c81
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f8be8f9120f
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f8be8f9118b
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f8be8f70858
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: lightningd/log.c:803 (fatal) 0x55eb54032721
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: lightningd/bitcoind.c:120 (bitcoin_plugin_error) 0x55eb5400a5c3
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: lightningd/bitcoind.c:534 (getutxout_callback) 0x55eb5400b2e4
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:460 (plugin_response_handle) 0x55eb54055100
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:566 (plugin_read_json_one) 0x55eb54055310
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:611 (plugin_read_json) 0x55eb540554da
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x55eb540d93bc
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:407 (do_plan) 0x55eb540d9fa1
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:417 (io_ready) 0x55eb540d9fe3
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: ccan/ccan/io/poll.c:445 (io_loop) 0x55eb540dc27b
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: lightningd/io_loop_with_timers.c:24 (io_loop_with_timers) 0x55eb5402a0d8
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: lightningd/lightningd.c:1102 (main) 0x55eb5402fc99
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f8be8f720b2
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x55eb54009ffd
2021-03-29T10:21:50.276Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0xffffffffffffffff
Log dumped in crash.log.20210329102150
spenderp: Lost connection to the RPC socket.
txprepare: pay: autoclean: Lost connection to the RPC socket.Lost connection to the RPC socket.

Lost connection to the RPC socket.
keysend: Lost connection to the RPC socket.
Aborted
```

**Comment by jsarenik** [comment] 2021-03-29 13:45
And another with the proper `object does not have member`, but now `amount`:

```
2021-03-29T13:39:25.877Z DEBUG   027455aef8453d92f4706b560b61527cc217ddf14da41770e8ed6607190a1851b8-gossipd: Updated pending announce with update 1562657x139x0/1
2021-03-29T13:39:25.878Z DEBUG   027455aef8453d92f4706b560b61527cc217ddf14da41770e8ed6607190a1851b8-gossipd: Received channel_announcement for channel 1562657x140x0
2021-03-29T13:39:25.879Z INFO    plugin-esplora: getutxout
/home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/esplora error: bad response to getutxout (bad 'result' field: Parsing '{result:{script:%,amount:': object does not have member amount), response was {"jsonrpc":"2.0","id":107,"result":{"script":"0020a40e801531fdca0fb550013a9140aaaf8d9eb106c427258fbc86d0e0c52c432d"} }
2021-03-29T13:39:25.880Z **BROKEN** lightningd: /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/esplora error: bad response to getutxout (bad 'result' field: Parsing '{result:{script:%,amount:': object does not have member amount), response was {"jsonrpc":"2.0","id":107,"result":{"script":"0020a40e801531fdca0fb550013a9140aaaf8d9eb106c427258fbc86d0e0c52c432d"} }
lightningd: FATAL SIGNAL 6 (version v0.10.0rc2-1-g4ac4168)
0x563a65fa7bd7 send_backtrace
	common/daemon.c:39
0x563a65fa7c81 crashdump
	common/daemon.c:52
0x7fe95a8c020f ???
	???:0
0x7fe95a8c018b ???
	???:0
0x7fe95a89f858 ???
	???:0
0x563a65f55721 fatal
	lightningd/log.c:803
0x563a65f2d5c3 bitcoin_plugin_error
	lightningd/bitcoind.c:120
0x563a65f2e2e4 getutxout_callback
	lightningd/bitcoind.c:534
0x563a65f78100 plugin_response_handle
	lightningd/plugin.c:460
0x563a65f78310 plugin_read_json_one
	lightningd/plugin.c:566
0x563a65f784da plugin_read_json
	lightningd/plugin.c:611
0x563a65ffc3bc next_plan
	ccan/ccan/io/io.c:59
0x563a65ffcfa1 do_plan
	ccan/ccan/io/io.c:407
0x563a65ffcfe3 io_ready
	ccan/ccan/io/io.c:417
0x563a65fff27b io_loop
	ccan/ccan/io/poll.c:445
0x563a65f4d0d8 io_loop_with_timers
	lightningd/io_loop_with_timers.c:24
0x563a65f52c99 main
	lightningd/lightningd.c:1102
0x7fe95a8a10b2 ???
	???:0
0x563a65f2cffd ???
	???:0
0xffffffffffffffff ???
	???:0
2021-03-29T13:39:25.895Z **BROKEN** lightningd: FATAL SIGNAL 6 (version v0.10.0rc2-1-g4ac4168)
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: common/daemon.c:44 (send_backtrace) 0x563a65fa7c2d
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: common/daemon.c:52 (crashdump) 0x563a65fa7c81
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fe95a8c020f
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fe95a8c018b
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fe95a89f858
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: lightningd/log.c:803 (fatal) 0x563a65f55721
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: lightningd/bitcoind.c:120 (bitcoin_plugin_error) 0x563a65f2d5c3
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: lightningd/bitcoind.c:534 (getutxout_callback) 0x563a65f2e2e4
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:460 (plugin_response_handle) 0x563a65f78100
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:566 (plugin_read_json_one) 0x563a65f78310
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:611 (plugin_read_json) 0x563a65f784da
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x563a65ffc3bc
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:407 (do_plan) 0x563a65ffcfa1
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:417 (io_ready) 0x563a65ffcfe3
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: ccan/ccan/io/poll.c:445 (io_loop) 0x563a65fff27b
2021-03-29T13:39:25.895Z **BROKEN** lightningd: backtrace: lightningd/io_loop_with_timers.c:24 (io_loop_with_timers) 0x563a65f4d0d8
2021-03-29T13:39:25.896Z **BROKEN** lightningd: backtrace: lightningd/lightningd.c:1102 (main) 0x563a65f52c99
2021-03-29T13:39:25.896Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fe95a8a10b2
2021-03-29T13:39:25.896Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x563a65f2cffd
2021-03-29T13:39:25.896Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0xffffffffffffffff
Log dumped in crash.log.20210329133925
pay: keysend: Lost connection to the RPC socket.
autoclean: Lost connection to the RPC socket.
Lost connection to the RPC socket.
Aborted
```

**Comment by lvaccaro** [comment] 2021-03-30 21:18
Hi @jsarenik , I am wasting a really huge amount of time trying to explore that bugs, that it looks not fixed and happen frequently to me.
Based on the logs, script looks parsed successfully from vout but not the amount.

**Comment by jsarenik** [comment] 2021-03-31 16:52
@lvaccaro Thank you for your time. Let me know if I can help with anything.

**Comment by lvaccaro** [comment] 2021-03-31 21:41
I added some logs in order to check the parsing the response of get transaction information in getutxoset() function.
I am able to print the amount value inside `output.amount.satoshis` :
```c
plugin_log(cmd->plugin, LOG_INFORM, ">> u64: %lu", output.amount.satoshis);
```
so the plugin is able to read & parse the `value` field of vout.

On the other hand, the `amount` field looks not present in the json response, added in line 586
https://github.com/lightningamp/esplora_clnd_plugin/blob/2bf24a303f82c1872332b2bdc3e178612c0e3c39/esplora.c#L586

**Comment by lvaccaro** [comment] 2021-03-31 22:00
Maybe the failure is related to the conversion, because bitcoind provides vout value as BTC and esplora provides as satoshi. So the api trying to convert esplora output, and it goes on overflow. It makes more sense to me.

**Comment by vincenzopalazzo** [comment] 2021-03-31 22:14
HI @lvaccaro,

Yest it make sense, and for me it is a concept ack. In this case the overflow happen inside the lightning structure that model the bitcoin transaction, right?

**Comment by lvaccaro** [comment] 2021-03-31 22:17
The error is this conversion 
https://github.com/lightningamp/esplora_clnd_plugin/blob/2bf24a303f82c1872332b2bdc3e178612c0e3c39/esplora.c#L556

Replace `json_to_bitcoin_amount` with `json_to_sat` should fix. I am testing locally.

**Comment by vincenzopalazzo** [comment] 2021-03-31 22:21
yep, if you want a node, you can use it

```
{
   "id": "03b39d1ddf13ce486de74e9e44e0538f960401a9ec75534ba9cfe4100d65426880",
   "alias": "SLICKERGOPHER",
   "color": "02bf81",
   "num_peers": 12,
   "num_pending_channels": 1,
   "num_active_channels": 11,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv3",
         "address": "iopzsfi3pbtrimnovncctjthmot7nb6pvh2swr6pqvizmisy4ts62lid.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9735
      }
   ],
   "version": "0.10.0",
   "blockheight": 1969110,
   "network": "testnet",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/media/vincent/Maxtor/C-lightning/node/testnet"
}
```

An this is an invoice on testnet

`lntb1psxfawspp5ky9kx6z0nk0slezvqvn7xyhynn83edvn7ejw7htc77zejk5l028sdq4wdhk6et5dp5kuem9d3ek2xqyjw5qcqp2sp5plwuyxcfmt5zxnanfaue3kcwm5c5nsa5t9g4y96jkc0q8jpvpwssrzjqwcnxzkap367pvhpgqwuvypg50fr2xulaape6upl0lm37wsc97gey8v7rvqqqxsqqyqqqqq2qqqq86qqqc9qy9qsqfluhya2axdkqyvksdngue5s40cq0yjyvxheds9yr2vj57mxjcwvn2zuc89tur4qpjae2t7fpxm869pz9qszlme5qreldvnrq2pk6rqsq2txyxj`

**Comment by lvaccaro** [comment] 2021-04-01 21:28
https://github.com/lightningamp/esplora_clnd_plugin/pull/48 should close the amount issue

**Comment by jsarenik** [comment] 2021-04-03 20:29
It is working well now with https://github.com/lightningamp/esplora_clnd_plugin/pull/49

**Comment by jsarenik** [comment] 2021-04-03 20:30
@lvaccaro thank you for the fix!

**Comment by lvaccaro** [comment] 2021-04-04 09:56
you are welcome. I close the issue for now

**Closed by lvaccaro** 2021-04-04 09:56 UTC
